spring.application.name=glpi_worker
spring.shell.script.enabled=true
spring.shell.interactive.enabled=true

spring.codec.log-request-details=true
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG

glpi.url: http://localhost
glpi.client-id: 2bbeb091700f3d9925de13ad128b53ee5ab7c1ba5e237ca705d2ef593f0b653d
glpi.client-secret: 13e4c75d75c182e4beca893b77956994b3df93f319f1386db0424b8f4abd93bd
glpi.username: API_usuario
glpi.password: 1
glpi.scope: api
glpi.api-endpoint: /api.php