services:
  glpi-automocao:
    image: glpi-automocao:latest
    build: .
    stdin_open: true
    tty: true
    environment:
      - glpi_url=http://localhost
      - glpi_endpoint=/api.php
      - glpi_client_id=${GLPI_CLIENT_ID}
      - glpi_client_secret=${GLPI_CLIENT_SECRET}
      - glpi_username=${GLPI_USERNAME}
      - glpi_password=${GLPI_PASSWORD}


#define a rede 
networks:
  glpi-mail:
    external: true